In [2]:
#Likhitha Vempati
#700757827

import numpy as np

#Create a random vector of size 15 with integers in the range 1-20
vector = np.random.randint(1, 21, size=15)
print("Random Vector of size 15:\n", vector)

#Reshape the array to 3 by 5
reshaped_array = vector.reshape(3, 5)
print("\nReshaped Array (3x5):\n", reshaped_array)

#Print the array shape
print("\nArray Shape:", reshaped_array.shape)

#Replace the max in each row by 0
for row in reshaped_array:
    row[row == np.max(row)] = 0


#Create a 2-dimensional array of size 4x3 composed of 4-byte integer elements
array_2d = np.zeros((4, 3), dtype=np.int32)
print("\n2-D Array (4x3):\n", array_2d)

# Print the shape, type, and data type of the array
print("\nArray Shape:", array_4x3.shape)
print("Array Type:", type(array_4x3))
print("Array Data Type:", array_4x3.dtype)


Random Vector of size 15:
 [16 14  9 17  5 19 16  1  9 13 20 16  5  9 16]

Reshaped Array (3x5):
 [[16 14  9 17  5]
 [19 16  1  9 13]
 [20 16  5  9 16]]

Array Shape: (3, 5)

2-D Array (4x3):
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

Array Shape: (4, 3)
Array Type: <class 'numpy.ndarray'>
Array Data Type: int32


In [3]:
import numpy as np

# Define the given square array
matrix = np.array([[3, -2], [1, 0]])

# Compute  eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Print the eigenvalues and right eigenvectors
print("Eigenvalues:\n", eigenvalues)
print("\nRight Eigenvectors:\n", eigenvectors)


Eigenvalues:
 [2. 1.]

Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [4]:
import numpy as np

# Define the array
arr = np.array([[0, 1, 2], [3, 4, 5]])

# Compute the sum of the diagonal elements
diagonal_sum = np.trace(arr)

# Print the sum of the diagonal elements
print("Sum of the diagonal elements:", diagonal_sum)


Sum of the diagonal elements: 4


In [5]:
import numpy as np

# Define the original 3x2 array
original_array = np.array([[1, 2], [3, 4], [5, 6]])

# Reshape the array to 2x3
reshaped_array = original_array.reshape(2, 3)

# Print the reshaped array
print("Original 3x2 array:\n", original_array)
print("\nReshaped 2x3 array:\n", reshaped_array)


Original 3x2 array:
 [[1 2]
 [3 4]
 [5 6]]

Reshaped 2x3 array:
 [[1 2 3]
 [4 5 6]]
